import AntDProvider from "@/components/shared/AntDProvider";
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import customAntTheme from "@/theme/ant-theme";
import ReactQueryProvider from "@/components/shared/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider theme={customAntTheme}>
          <ReactQueryProvider>
            <AntDProvider>{children}</AntDProvider>
          </ReactQueryProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
