import AntDProvider from "@/components/shared/AntDProvider";
import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider, theme, ThemeConfig } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const customTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: "#722ED1",
    borderRadius: 8,
    colorTextLightSolid: "#ffffff",
    controlHeight: 32,
    boxShadowSecondary: "0px 2px 0px rgba(0, 0, 0, 0.043)",
  },
  components: {
    Button: {
      colorPrimary: "#722ED1",
      colorPrimaryHover: "#925FF0",
      colorPrimaryActive: "#5D19B4",
      boxShadow: "0px 2px 0px rgba(0, 0, 0, 0.043)",
      borderRadius: 8,
      paddingInline: 15,
      paddingBlock: 4,
      controlHeight: 32,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider theme={customTheme}>
          <AntDProvider>{children}</AntDProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
