create table "public"."purchase_order" (
    "id" bigint generated by default as identity not null,
    "purchase_order_no" text not null,
    "supplier_id" bigint not null,
    "region_id" bigint not null,
    "budget_id" integer not null,
    "order_date" date not null,
    "currency_id" bigint not null,
    "usd_exchange_rate" numeric(12,6) not null,
    "contact_person_name" text not null,
    "sign_person_name" text,
    "authorized_signer_name" text,
    "status" text not null default 'Draft'::text,
    "note" text,
    "expected_delivery_date" date not null,
    "items" json not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


CREATE UNIQUE INDEX purchase_order_pkey ON public.purchase_order USING btree (id);

CREATE UNIQUE INDEX purchase_order_purchase_order_no_key ON public.purchase_order USING btree (purchase_order_no);

alter table "public"."purchase_order" add constraint "purchase_order_pkey" PRIMARY KEY using index "purchase_order_pkey";

alter table "public"."purchase_order" add constraint "purchase_order_currency_id_fkey" FOREIGN KEY (currency_id) REFERENCES product_currency(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_currency_id_fkey";

alter table "public"."purchase_order" add constraint "purchase_order_purchase_order_no_key" UNIQUE using index "purchase_order_purchase_order_no_key";

alter table "public"."purchase_order" add constraint "purchase_order_region_id_fkey" FOREIGN KEY (region_id) REFERENCES purchase_order_region(id) ON DELETE RESTRICT not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_region_id_fkey";

alter table "public"."purchase_order" add constraint "purchase_order_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE RESTRICT not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_supplier_id_fkey";

grant delete on table "public"."purchase_order" to "anon";

grant insert on table "public"."purchase_order" to "anon";

grant references on table "public"."purchase_order" to "anon";

grant select on table "public"."purchase_order" to "anon";

grant trigger on table "public"."purchase_order" to "anon";

grant truncate on table "public"."purchase_order" to "anon";

grant update on table "public"."purchase_order" to "anon";

grant delete on table "public"."purchase_order" to "authenticated";

grant insert on table "public"."purchase_order" to "authenticated";

grant references on table "public"."purchase_order" to "authenticated";

grant select on table "public"."purchase_order" to "authenticated";

grant trigger on table "public"."purchase_order" to "authenticated";

grant truncate on table "public"."purchase_order" to "authenticated";

grant update on table "public"."purchase_order" to "authenticated";

grant delete on table "public"."purchase_order" to "service_role";

grant insert on table "public"."purchase_order" to "service_role";

grant references on table "public"."purchase_order" to "service_role";

grant select on table "public"."purchase_order" to "service_role";

grant trigger on table "public"."purchase_order" to "service_role";

grant truncate on table "public"."purchase_order" to "service_role";

grant update on table "public"."purchase_order" to "service_role";


