create table "public"."currency" (
    "id" bigint generated by default as identity not null,
    "currency_code" character varying(10) not null,
    "currency_name" character varying(50) not null,
    "is_active" boolean default true,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);


alter table "public"."product" add column "description" text;

alter table "public"."product" add column "stock" integer default 0;

CREATE UNIQUE INDEX currency_currency_code_key ON public.currency USING btree (currency_code);

CREATE UNIQUE INDEX currency_pkey ON public.currency USING btree (id);

alter table "public"."currency" add constraint "currency_pkey" PRIMARY KEY using index "currency_pkey";

alter table "public"."currency" add constraint "currency_currency_code_key" UNIQUE using index "currency_currency_code_key";

grant delete on table "public"."currency" to "anon";

grant insert on table "public"."currency" to "anon";

grant references on table "public"."currency" to "anon";

grant select on table "public"."currency" to "anon";

grant trigger on table "public"."currency" to "anon";

grant truncate on table "public"."currency" to "anon";

grant update on table "public"."currency" to "anon";

grant delete on table "public"."currency" to "authenticated";

grant insert on table "public"."currency" to "authenticated";

grant references on table "public"."currency" to "authenticated";

grant select on table "public"."currency" to "authenticated";

grant trigger on table "public"."currency" to "authenticated";

grant truncate on table "public"."currency" to "authenticated";

grant update on table "public"."currency" to "authenticated";

grant delete on table "public"."currency" to "service_role";

grant insert on table "public"."currency" to "service_role";

grant references on table "public"."currency" to "service_role";

grant select on table "public"."currency" to "service_role";

grant trigger on table "public"."currency" to "service_role";

grant truncate on table "public"."currency" to "service_role";

grant update on table "public"."currency" to "service_role";


