create table "public"."pruchase_orders_item_audit_log" (
    "id" bigint generated by default as identity not null,
    "purchase_order_id" bigint not null,
    "changed_by" uuid,
    "changed_field" text,
    "old_values" text,
    "new_values" text,
    "changed_at" timestamp with time zone default timezone('utc'::text, now()),
    "purchase_order_item_id" bigint
);


CREATE UNIQUE INDEX pruchase_orders_item_audit_log_pkey ON public.pruchase_orders_item_audit_log USING btree (id);

alter table "public"."pruchase_orders_item_audit_log" add constraint "pruchase_orders_item_audit_log_pkey" PRIMARY KEY using index "pruchase_orders_item_audit_log_pkey";

alter table "public"."pruchase_orders_item_audit_log" add constraint "pruchase_orders_item_audit_log_purchase_order_id_fkey" FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id) not valid;

alter table "public"."pruchase_orders_item_audit_log" validate constraint "pruchase_orders_item_audit_log_purchase_order_id_fkey";

alter table "public"."pruchase_orders_item_audit_log" add constraint "pruchase_orders_item_audit_log_purchase_order_item_id_fkey" FOREIGN KEY (purchase_order_item_id) REFERENCES purchase_order_items(id) not valid;

alter table "public"."pruchase_orders_item_audit_log" validate constraint "pruchase_orders_item_audit_log_purchase_order_item_id_fkey";

grant delete on table "public"."pruchase_orders_item_audit_log" to "anon";

grant insert on table "public"."pruchase_orders_item_audit_log" to "anon";

grant references on table "public"."pruchase_orders_item_audit_log" to "anon";

grant select on table "public"."pruchase_orders_item_audit_log" to "anon";

grant trigger on table "public"."pruchase_orders_item_audit_log" to "anon";

grant truncate on table "public"."pruchase_orders_item_audit_log" to "anon";

grant update on table "public"."pruchase_orders_item_audit_log" to "anon";

grant delete on table "public"."pruchase_orders_item_audit_log" to "authenticated";

grant insert on table "public"."pruchase_orders_item_audit_log" to "authenticated";

grant references on table "public"."pruchase_orders_item_audit_log" to "authenticated";

grant select on table "public"."pruchase_orders_item_audit_log" to "authenticated";

grant trigger on table "public"."pruchase_orders_item_audit_log" to "authenticated";

grant truncate on table "public"."pruchase_orders_item_audit_log" to "authenticated";

grant update on table "public"."pruchase_orders_item_audit_log" to "authenticated";

grant delete on table "public"."pruchase_orders_item_audit_log" to "service_role";

grant insert on table "public"."pruchase_orders_item_audit_log" to "service_role";

grant references on table "public"."pruchase_orders_item_audit_log" to "service_role";

grant select on table "public"."pruchase_orders_item_audit_log" to "service_role";

grant trigger on table "public"."pruchase_orders_item_audit_log" to "service_role";

grant truncate on table "public"."pruchase_orders_item_audit_log" to "service_role";

grant update on table "public"."pruchase_orders_item_audit_log" to "service_role";


