create table "public"."purchase_order_update_reason" (
    "id" bigint generated by default as identity not null,
    "purchase_order_id" bigint not null,
    "reason" text not null,
    "action" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."purchase_order_update_reason" enable row level security;

CREATE UNIQUE INDEX purchase_order_update_reason_pkey ON public.purchase_order_update_reason USING btree (id);

alter table "public"."purchase_order_update_reason" add constraint "purchase_order_update_reason_pkey" PRIMARY KEY using index "purchase_order_update_reason_pkey";

alter table "public"."purchase_order_update_reason" add constraint "purchase_order_update_reason_purchase_order_id_fkey" FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."purchase_order_update_reason" validate constraint "purchase_order_update_reason_purchase_order_id_fkey";

grant delete on table "public"."purchase_order_update_reason" to "anon";

grant insert on table "public"."purchase_order_update_reason" to "anon";

grant references on table "public"."purchase_order_update_reason" to "anon";

grant select on table "public"."purchase_order_update_reason" to "anon";

grant trigger on table "public"."purchase_order_update_reason" to "anon";

grant truncate on table "public"."purchase_order_update_reason" to "anon";

grant update on table "public"."purchase_order_update_reason" to "anon";

grant delete on table "public"."purchase_order_update_reason" to "authenticated";

grant insert on table "public"."purchase_order_update_reason" to "authenticated";

grant references on table "public"."purchase_order_update_reason" to "authenticated";

grant select on table "public"."purchase_order_update_reason" to "authenticated";

grant trigger on table "public"."purchase_order_update_reason" to "authenticated";

grant truncate on table "public"."purchase_order_update_reason" to "authenticated";

grant update on table "public"."purchase_order_update_reason" to "authenticated";

grant delete on table "public"."purchase_order_update_reason" to "service_role";

grant insert on table "public"."purchase_order_update_reason" to "service_role";

grant references on table "public"."purchase_order_update_reason" to "service_role";

grant select on table "public"."purchase_order_update_reason" to "service_role";

grant trigger on table "public"."purchase_order_update_reason" to "service_role";

grant truncate on table "public"."purchase_order_update_reason" to "service_role";

grant update on table "public"."purchase_order_update_reason" to "service_role";


