revoke delete on table "public"."currency" from "anon";

revoke insert on table "public"."currency" from "anon";

revoke references on table "public"."currency" from "anon";

revoke select on table "public"."currency" from "anon";

revoke trigger on table "public"."currency" from "anon";

revoke truncate on table "public"."currency" from "anon";

revoke update on table "public"."currency" from "anon";

revoke delete on table "public"."currency" from "authenticated";

revoke insert on table "public"."currency" from "authenticated";

revoke references on table "public"."currency" from "authenticated";

revoke select on table "public"."currency" from "authenticated";

revoke trigger on table "public"."currency" from "authenticated";

revoke truncate on table "public"."currency" from "authenticated";

revoke update on table "public"."currency" from "authenticated";

revoke delete on table "public"."currency" from "service_role";

revoke insert on table "public"."currency" from "service_role";

revoke references on table "public"."currency" from "service_role";

revoke select on table "public"."currency" from "service_role";

revoke trigger on table "public"."currency" from "service_role";

revoke truncate on table "public"."currency" from "service_role";

revoke update on table "public"."currency" from "service_role";

alter table "public"."currency" drop constraint "currency_currency_code_key";

alter table "public"."currency" drop constraint "currency_pkey";

drop index if exists "public"."currency_currency_code_key";

drop index if exists "public"."currency_pkey";

drop table "public"."currency";

create table "public"."product_currency" (
    "id" bigint generated by default as identity not null,
    "currency_code" character varying(10) not null,
    "currency_name" character varying(50) not null,
    "is_active" boolean default true,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);


CREATE UNIQUE INDEX currency_currency_code_key ON public.product_currency USING btree (currency_code);

CREATE UNIQUE INDEX currency_pkey ON public.product_currency USING btree (id);

alter table "public"."product_currency" add constraint "currency_pkey" PRIMARY KEY using index "currency_pkey";

alter table "public"."product_currency" add constraint "currency_currency_code_key" UNIQUE using index "currency_currency_code_key";

grant delete on table "public"."product_currency" to "anon";

grant insert on table "public"."product_currency" to "anon";

grant references on table "public"."product_currency" to "anon";

grant select on table "public"."product_currency" to "anon";

grant trigger on table "public"."product_currency" to "anon";

grant truncate on table "public"."product_currency" to "anon";

grant update on table "public"."product_currency" to "anon";

grant delete on table "public"."product_currency" to "authenticated";

grant insert on table "public"."product_currency" to "authenticated";

grant references on table "public"."product_currency" to "authenticated";

grant select on table "public"."product_currency" to "authenticated";

grant trigger on table "public"."product_currency" to "authenticated";

grant truncate on table "public"."product_currency" to "authenticated";

grant update on table "public"."product_currency" to "authenticated";

grant delete on table "public"."product_currency" to "service_role";

grant insert on table "public"."product_currency" to "service_role";

grant references on table "public"."product_currency" to "service_role";

grant select on table "public"."product_currency" to "service_role";

grant trigger on table "public"."product_currency" to "service_role";

grant truncate on table "public"."product_currency" to "service_role";

grant update on table "public"."product_currency" to "service_role";


