create table "public"."stock_transaction_audit_log" (
    "id" bigint generated by default as identity not null,
    "transaction_id" bigint not null,
    "changed_by" uuid not null,
    "changed_field" text not null,
    "old_values" text not null,
    "new_values" text not null,
    "changed_at" timestamp with time zone not null default now()
);


alter table "public"."stock_transaction_audit_log" enable row level security;

CREATE UNIQUE INDEX stock_transaction_audit_log_pkey ON public.stock_transaction_audit_log USING btree (id);

alter table "public"."stock_transaction_audit_log" add constraint "stock_transaction_audit_log_pkey" PRIMARY KEY using index "stock_transaction_audit_log_pkey";

alter table "public"."stock_transaction_audit_log" add constraint "stock_transaction_audit_log_changed_by_fkey" FOREIGN KEY (changed_by) REFERENCES user_profiles(id) not valid;

alter table "public"."stock_transaction_audit_log" validate constraint "stock_transaction_audit_log_changed_by_fkey";

alter table "public"."stock_transaction_audit_log" add constraint "stock_transaction_audit_log_transaction_id_fkey" FOREIGN KEY (transaction_id) REFERENCES stock_transaction(id) not valid;

alter table "public"."stock_transaction_audit_log" validate constraint "stock_transaction_audit_log_transaction_id_fkey";

grant delete on table "public"."stock_transaction_audit_log" to "anon";

grant insert on table "public"."stock_transaction_audit_log" to "anon";

grant references on table "public"."stock_transaction_audit_log" to "anon";

grant select on table "public"."stock_transaction_audit_log" to "anon";

grant trigger on table "public"."stock_transaction_audit_log" to "anon";

grant truncate on table "public"."stock_transaction_audit_log" to "anon";

grant update on table "public"."stock_transaction_audit_log" to "anon";

grant delete on table "public"."stock_transaction_audit_log" to "authenticated";

grant insert on table "public"."stock_transaction_audit_log" to "authenticated";

grant references on table "public"."stock_transaction_audit_log" to "authenticated";

grant select on table "public"."stock_transaction_audit_log" to "authenticated";

grant trigger on table "public"."stock_transaction_audit_log" to "authenticated";

grant truncate on table "public"."stock_transaction_audit_log" to "authenticated";

grant update on table "public"."stock_transaction_audit_log" to "authenticated";

grant delete on table "public"."stock_transaction_audit_log" to "service_role";

grant insert on table "public"."stock_transaction_audit_log" to "service_role";

grant references on table "public"."stock_transaction_audit_log" to "service_role";

grant select on table "public"."stock_transaction_audit_log" to "service_role";

grant trigger on table "public"."stock_transaction_audit_log" to "service_role";

grant truncate on table "public"."stock_transaction_audit_log" to "service_role";

grant update on table "public"."stock_transaction_audit_log" to "service_role";

alter table "public"."stock_transaction_audit_log" disable row level security;
