alter table "public"."budgets" drop constraint "budgets_status_check";

create table "public"."budget_allocation" (
    "id" bigint generated by default as identity not null,
    "po_id" bigint not null,
    "allocation_amount" numeric not null,
    "currency_code" character varying not null,
    "exchange_rate_usd" numeric(15,6) not null,
    "transfer_evidence" text not null,
    "status" text default 'Pending'::text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "budget_id" bigint,
    "allocation_number" text not null,
    "allocation_date" date not null,
    "created_by" uuid,
    "equivalent_usd" numeric generated always as ((allocation_amount / exchange_rate_usd)) stored
);


create table "public"."budget_allocation_activity_logs" (
    "id" bigint generated by default as identity not null,
    "allocation_id" bigint,
    "po_id" bigint,
    "user_id" uuid not null,
    "role" text not null,
    "action_type" text,
    "amount" numeric,
    "currency_code" text,
    "notes" text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
);


create table "public"."person" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);


create table "public"."pruchase_orders_audit_log" (
    "id" bigint generated by default as identity not null,
    "purchase_order_id" bigint not null,
    "changed_by" uuid,
    "changed_field" text,
    "old_values" text,
    "new_values" text,
    "changed_at" timestamp with time zone default timezone('utc'::text, now())
);


create table "public"."purchase_order" (
    "id" bigint generated by default as identity not null,
    "purchase_order_no" text not null,
    "supplier_id" bigint not null,
    "region_id" bigint not null,
    "budget_id" integer not null,
    "order_date" date not null,
    "currency_id" bigint not null,
    "usd_exchange_rate" numeric(12,6) not null,
    "status" text not null default 'Draft'::text,
    "note" text,
    "expected_delivery_date" date not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "authorized_signer_id" bigint,
    "contact_person_id" bigint not null,
    "sign_person_id" bigint
);


create table "public"."purchase_order_drafts" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "po_number" text,
    "supplier_id" bigint,
    "region_id" bigint,
    "budget_id" integer,
    "order_date" date,
    "currency_id" bigint,
    "usd_exchange_rate" numeric(12,6),
    "contact_person_id" bigint,
    "sign_person_id" bigint,
    "authorized_signer_id" bigint,
    "expected_delivery_date" date,
    "note" text,
    "form_data" jsonb not null default '{}'::jsonb,
    "current_step" integer not null default 0,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


create table "public"."purchase_order_items" (
    "id" bigint generated by default as identity not null,
    "purchase_order_id" bigint not null,
    "product_id" bigint not null,
    "quantity" integer not null,
    "unit_price_local" numeric(12,6) not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);


create table "public"."purchase_order_region" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


alter table "public"."budget_allocations" alter column "created_at" set default now();

alter table "public"."budget_allocations" alter column "created_at" drop not null;

alter table "public"."budget_invoices" alter column "created_at" set default now();

alter table "public"."budget_invoices" alter column "created_at" drop not null;

alter table "public"."budgets" alter column "status" drop default;

alter table "public"."budgets" alter column "status" drop not null;

alter table "public"."budgets" alter column "status" set data type boolean using "status"::boolean;

CREATE UNIQUE INDEX budget_allocation_activity_logs_pkey ON public.budget_allocation_activity_logs USING btree (id);

CREATE UNIQUE INDEX budget_allocation_pkey ON public.budget_allocation USING btree (id);

CREATE UNIQUE INDEX person_pkey ON public.person USING btree (id);

CREATE UNIQUE INDEX pruchase_orders_audit_log_pkey ON public.pruchase_orders_audit_log USING btree (id);

CREATE INDEX purchase_order_drafts_created_at_idx ON public.purchase_order_drafts USING btree (created_at);

CREATE UNIQUE INDEX purchase_order_drafts_pkey ON public.purchase_order_drafts USING btree (id);

CREATE INDEX purchase_order_drafts_user_id_idx ON public.purchase_order_drafts USING btree (user_id);

CREATE UNIQUE INDEX purchase_order_items_pkey ON public.purchase_order_items USING btree (id);

CREATE UNIQUE INDEX purchase_order_pkey ON public.purchase_order USING btree (id);

CREATE UNIQUE INDEX purchase_order_purchase_order_no_key ON public.purchase_order USING btree (purchase_order_no);

CREATE UNIQUE INDEX purchase_order_region_pkey ON public.purchase_order_region USING btree (id);

alter table "public"."budget_allocation" add constraint "budget_allocation_pkey" PRIMARY KEY using index "budget_allocation_pkey";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_pkey" PRIMARY KEY using index "budget_allocation_activity_logs_pkey";

alter table "public"."person" add constraint "person_pkey" PRIMARY KEY using index "person_pkey";

alter table "public"."pruchase_orders_audit_log" add constraint "pruchase_orders_audit_log_pkey" PRIMARY KEY using index "pruchase_orders_audit_log_pkey";

alter table "public"."purchase_order" add constraint "purchase_order_pkey" PRIMARY KEY using index "purchase_order_pkey";

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_pkey" PRIMARY KEY using index "purchase_order_drafts_pkey";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_pkey" PRIMARY KEY using index "purchase_order_items_pkey";

alter table "public"."purchase_order_region" add constraint "purchase_order_region_pkey" PRIMARY KEY using index "purchase_order_region_pkey";

alter table "public"."budget_allocation" add constraint "budget_allocation_allocation_amount_check" CHECK ((allocation_amount > (0)::numeric)) not valid;

alter table "public"."budget_allocation" validate constraint "budget_allocation_allocation_amount_check";

alter table "public"."budget_allocation" add constraint "budget_allocation_created_by_fkey" FOREIGN KEY (created_by) REFERENCES profiles(id) not valid;

alter table "public"."budget_allocation" validate constraint "budget_allocation_created_by_fkey";

alter table "public"."budget_allocation" add constraint "budget_allocation_exchange_rate_usd_check" CHECK ((exchange_rate_usd > (0)::numeric)) not valid;

alter table "public"."budget_allocation" validate constraint "budget_allocation_exchange_rate_usd_check";

alter table "public"."budget_allocation" add constraint "budget_allocation_po_id_fkey" FOREIGN KEY (po_id) REFERENCES purchase_order(id) not valid;

alter table "public"."budget_allocation" validate constraint "budget_allocation_po_id_fkey";

alter table "public"."budget_allocation" add constraint "budget_allocation_status_check" CHECK ((status = ANY (ARRAY['Pending'::text, 'Paid'::text, 'Canceled'::text]))) not valid;

alter table "public"."budget_allocation" validate constraint "budget_allocation_status_check";

alter table "public"."budget_allocation" add constraint "fk_allocations_budget" FOREIGN KEY (budget_id) REFERENCES budgets(id) not valid;

alter table "public"."budget_allocation" validate constraint "fk_allocations_budget";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_action_type_check" CHECK ((action_type = ANY (ARRAY['Create'::text, 'Cancel'::text, 'Update'::text]))) not valid;

alter table "public"."budget_allocation_activity_logs" validate constraint "budget_allocation_activity_logs_action_type_check";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_allocation_id_fkey" FOREIGN KEY (allocation_id) REFERENCES budget_allocation(id) not valid;

alter table "public"."budget_allocation_activity_logs" validate constraint "budget_allocation_activity_logs_allocation_id_fkey";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_po_id_fkey" FOREIGN KEY (po_id) REFERENCES purchase_order(id) not valid;

alter table "public"."budget_allocation_activity_logs" validate constraint "budget_allocation_activity_logs_po_id_fkey";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."budget_allocation_activity_logs" validate constraint "budget_allocation_activity_logs_user_id_fkey";

alter table "public"."purchase_order" add constraint "fk_po_budget" FOREIGN KEY (budget_id) REFERENCES budgets(id) not valid;

alter table "public"."purchase_order" validate constraint "fk_po_budget";

alter table "public"."purchase_order" add constraint "purchase_order_authorized_signer_id_fkey" FOREIGN KEY (authorized_signer_id) REFERENCES person(id) not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_authorized_signer_id_fkey";

alter table "public"."purchase_order" add constraint "purchase_order_contact_person_id_fkey" FOREIGN KEY (contact_person_id) REFERENCES person(id) not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_contact_person_id_fkey";

alter table "public"."purchase_order" add constraint "purchase_order_currency_id_fkey" FOREIGN KEY (currency_id) REFERENCES product_currency(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_currency_id_fkey";

alter table "public"."purchase_order" add constraint "purchase_order_purchase_order_no_key" UNIQUE using index "purchase_order_purchase_order_no_key";

alter table "public"."purchase_order" add constraint "purchase_order_region_id_fkey" FOREIGN KEY (region_id) REFERENCES purchase_order_region(id) ON DELETE RESTRICT not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_region_id_fkey";

alter table "public"."purchase_order" add constraint "purchase_order_sign_person_id_fkey" FOREIGN KEY (sign_person_id) REFERENCES person(id) not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_sign_person_id_fkey";

alter table "public"."purchase_order" add constraint "purchase_order_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE RESTRICT not valid;

alter table "public"."purchase_order" validate constraint "purchase_order_supplier_id_fkey";

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_authorized_signer_id_fkey" FOREIGN KEY (authorized_signer_id) REFERENCES person(id) ON DELETE SET NULL NOT VALID not valid;

alter table "public"."purchase_order_drafts" validate constraint "purchase_order_drafts_authorized_signer_id_fkey";

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_contact_person_id_fkey" FOREIGN KEY (contact_person_id) REFERENCES person(id) ON DELETE SET NULL NOT VALID not valid;

alter table "public"."purchase_order_drafts" validate constraint "purchase_order_drafts_contact_person_id_fkey";

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_currency_id_fkey" FOREIGN KEY (currency_id) REFERENCES product_currency(id) ON DELETE SET NULL NOT VALID not valid;

alter table "public"."purchase_order_drafts" validate constraint "purchase_order_drafts_currency_id_fkey";

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_region_id_fkey" FOREIGN KEY (region_id) REFERENCES purchase_order_region(id) ON DELETE SET NULL NOT VALID not valid;

alter table "public"."purchase_order_drafts" validate constraint "purchase_order_drafts_region_id_fkey";

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_sign_person_id_fkey" FOREIGN KEY (sign_person_id) REFERENCES person(id) ON DELETE SET NULL NOT VALID not valid;

alter table "public"."purchase_order_drafts" validate constraint "purchase_order_drafts_sign_person_id_fkey";

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE SET NULL NOT VALID not valid;

alter table "public"."purchase_order_drafts" validate constraint "purchase_order_drafts_supplier_id_fkey";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE RESTRICT not valid;

alter table "public"."purchase_order_items" validate constraint "purchase_order_items_product_id_fkey";

alter table "public"."purchase_order_items" add constraint "purchase_order_items_purchase_order_id_fkey" FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id) ON DELETE RESTRICT not valid;

alter table "public"."purchase_order_items" validate constraint "purchase_order_items_purchase_order_id_fkey";

grant delete on table "public"."budget_allocation" to "anon";

grant insert on table "public"."budget_allocation" to "anon";

grant references on table "public"."budget_allocation" to "anon";

grant select on table "public"."budget_allocation" to "anon";

grant trigger on table "public"."budget_allocation" to "anon";

grant truncate on table "public"."budget_allocation" to "anon";

grant update on table "public"."budget_allocation" to "anon";

grant delete on table "public"."budget_allocation" to "authenticated";

grant insert on table "public"."budget_allocation" to "authenticated";

grant references on table "public"."budget_allocation" to "authenticated";

grant select on table "public"."budget_allocation" to "authenticated";

grant trigger on table "public"."budget_allocation" to "authenticated";

grant truncate on table "public"."budget_allocation" to "authenticated";

grant update on table "public"."budget_allocation" to "authenticated";

grant delete on table "public"."budget_allocation" to "service_role";

grant insert on table "public"."budget_allocation" to "service_role";

grant references on table "public"."budget_allocation" to "service_role";

grant select on table "public"."budget_allocation" to "service_role";

grant trigger on table "public"."budget_allocation" to "service_role";

grant truncate on table "public"."budget_allocation" to "service_role";

grant update on table "public"."budget_allocation" to "service_role";

grant delete on table "public"."budget_allocation_activity_logs" to "anon";

grant insert on table "public"."budget_allocation_activity_logs" to "anon";

grant references on table "public"."budget_allocation_activity_logs" to "anon";

grant select on table "public"."budget_allocation_activity_logs" to "anon";

grant trigger on table "public"."budget_allocation_activity_logs" to "anon";

grant truncate on table "public"."budget_allocation_activity_logs" to "anon";

grant update on table "public"."budget_allocation_activity_logs" to "anon";

grant delete on table "public"."budget_allocation_activity_logs" to "authenticated";

grant insert on table "public"."budget_allocation_activity_logs" to "authenticated";

grant references on table "public"."budget_allocation_activity_logs" to "authenticated";

grant select on table "public"."budget_allocation_activity_logs" to "authenticated";

grant trigger on table "public"."budget_allocation_activity_logs" to "authenticated";

grant truncate on table "public"."budget_allocation_activity_logs" to "authenticated";

grant update on table "public"."budget_allocation_activity_logs" to "authenticated";

grant delete on table "public"."budget_allocation_activity_logs" to "service_role";

grant insert on table "public"."budget_allocation_activity_logs" to "service_role";

grant references on table "public"."budget_allocation_activity_logs" to "service_role";

grant select on table "public"."budget_allocation_activity_logs" to "service_role";

grant trigger on table "public"."budget_allocation_activity_logs" to "service_role";

grant truncate on table "public"."budget_allocation_activity_logs" to "service_role";

grant update on table "public"."budget_allocation_activity_logs" to "service_role";

grant delete on table "public"."person" to "anon";

grant insert on table "public"."person" to "anon";

grant references on table "public"."person" to "anon";

grant select on table "public"."person" to "anon";

grant trigger on table "public"."person" to "anon";

grant truncate on table "public"."person" to "anon";

grant update on table "public"."person" to "anon";

grant delete on table "public"."person" to "authenticated";

grant insert on table "public"."person" to "authenticated";

grant references on table "public"."person" to "authenticated";

grant select on table "public"."person" to "authenticated";

grant trigger on table "public"."person" to "authenticated";

grant truncate on table "public"."person" to "authenticated";

grant update on table "public"."person" to "authenticated";

grant delete on table "public"."person" to "service_role";

grant insert on table "public"."person" to "service_role";

grant references on table "public"."person" to "service_role";

grant select on table "public"."person" to "service_role";

grant trigger on table "public"."person" to "service_role";

grant truncate on table "public"."person" to "service_role";

grant update on table "public"."person" to "service_role";

grant delete on table "public"."pruchase_orders_audit_log" to "anon";

grant insert on table "public"."pruchase_orders_audit_log" to "anon";

grant references on table "public"."pruchase_orders_audit_log" to "anon";

grant select on table "public"."pruchase_orders_audit_log" to "anon";

grant trigger on table "public"."pruchase_orders_audit_log" to "anon";

grant truncate on table "public"."pruchase_orders_audit_log" to "anon";

grant update on table "public"."pruchase_orders_audit_log" to "anon";

grant delete on table "public"."pruchase_orders_audit_log" to "authenticated";

grant insert on table "public"."pruchase_orders_audit_log" to "authenticated";

grant references on table "public"."pruchase_orders_audit_log" to "authenticated";

grant select on table "public"."pruchase_orders_audit_log" to "authenticated";

grant trigger on table "public"."pruchase_orders_audit_log" to "authenticated";

grant truncate on table "public"."pruchase_orders_audit_log" to "authenticated";

grant update on table "public"."pruchase_orders_audit_log" to "authenticated";

grant delete on table "public"."pruchase_orders_audit_log" to "service_role";

grant insert on table "public"."pruchase_orders_audit_log" to "service_role";

grant references on table "public"."pruchase_orders_audit_log" to "service_role";

grant select on table "public"."pruchase_orders_audit_log" to "service_role";

grant trigger on table "public"."pruchase_orders_audit_log" to "service_role";

grant truncate on table "public"."pruchase_orders_audit_log" to "service_role";

grant update on table "public"."pruchase_orders_audit_log" to "service_role";

grant delete on table "public"."purchase_order" to "anon";

grant insert on table "public"."purchase_order" to "anon";

grant references on table "public"."purchase_order" to "anon";

grant select on table "public"."purchase_order" to "anon";

grant trigger on table "public"."purchase_order" to "anon";

grant truncate on table "public"."purchase_order" to "anon";

grant update on table "public"."purchase_order" to "anon";

grant delete on table "public"."purchase_order" to "authenticated";

grant insert on table "public"."purchase_order" to "authenticated";

grant references on table "public"."purchase_order" to "authenticated";

grant select on table "public"."purchase_order" to "authenticated";

grant trigger on table "public"."purchase_order" to "authenticated";

grant truncate on table "public"."purchase_order" to "authenticated";

grant update on table "public"."purchase_order" to "authenticated";

grant delete on table "public"."purchase_order" to "service_role";

grant insert on table "public"."purchase_order" to "service_role";

grant references on table "public"."purchase_order" to "service_role";

grant select on table "public"."purchase_order" to "service_role";

grant trigger on table "public"."purchase_order" to "service_role";

grant truncate on table "public"."purchase_order" to "service_role";

grant update on table "public"."purchase_order" to "service_role";

grant delete on table "public"."purchase_order_drafts" to "anon";

grant insert on table "public"."purchase_order_drafts" to "anon";

grant references on table "public"."purchase_order_drafts" to "anon";

grant select on table "public"."purchase_order_drafts" to "anon";

grant trigger on table "public"."purchase_order_drafts" to "anon";

grant truncate on table "public"."purchase_order_drafts" to "anon";

grant update on table "public"."purchase_order_drafts" to "anon";

grant delete on table "public"."purchase_order_drafts" to "authenticated";

grant insert on table "public"."purchase_order_drafts" to "authenticated";

grant references on table "public"."purchase_order_drafts" to "authenticated";

grant select on table "public"."purchase_order_drafts" to "authenticated";

grant trigger on table "public"."purchase_order_drafts" to "authenticated";

grant truncate on table "public"."purchase_order_drafts" to "authenticated";

grant update on table "public"."purchase_order_drafts" to "authenticated";

grant delete on table "public"."purchase_order_drafts" to "service_role";

grant insert on table "public"."purchase_order_drafts" to "service_role";

grant references on table "public"."purchase_order_drafts" to "service_role";

grant select on table "public"."purchase_order_drafts" to "service_role";

grant trigger on table "public"."purchase_order_drafts" to "service_role";

grant truncate on table "public"."purchase_order_drafts" to "service_role";

grant update on table "public"."purchase_order_drafts" to "service_role";

grant delete on table "public"."purchase_order_items" to "anon";

grant insert on table "public"."purchase_order_items" to "anon";

grant references on table "public"."purchase_order_items" to "anon";

grant select on table "public"."purchase_order_items" to "anon";

grant trigger on table "public"."purchase_order_items" to "anon";

grant truncate on table "public"."purchase_order_items" to "anon";

grant update on table "public"."purchase_order_items" to "anon";

grant delete on table "public"."purchase_order_items" to "authenticated";

grant insert on table "public"."purchase_order_items" to "authenticated";

grant references on table "public"."purchase_order_items" to "authenticated";

grant select on table "public"."purchase_order_items" to "authenticated";

grant trigger on table "public"."purchase_order_items" to "authenticated";

grant truncate on table "public"."purchase_order_items" to "authenticated";

grant update on table "public"."purchase_order_items" to "authenticated";

grant delete on table "public"."purchase_order_items" to "service_role";

grant insert on table "public"."purchase_order_items" to "service_role";

grant references on table "public"."purchase_order_items" to "service_role";

grant select on table "public"."purchase_order_items" to "service_role";

grant trigger on table "public"."purchase_order_items" to "service_role";

grant truncate on table "public"."purchase_order_items" to "service_role";

grant update on table "public"."purchase_order_items" to "service_role";

grant delete on table "public"."purchase_order_region" to "anon";

grant insert on table "public"."purchase_order_region" to "anon";

grant references on table "public"."purchase_order_region" to "anon";

grant select on table "public"."purchase_order_region" to "anon";

grant trigger on table "public"."purchase_order_region" to "anon";

grant truncate on table "public"."purchase_order_region" to "anon";

grant update on table "public"."purchase_order_region" to "anon";

grant delete on table "public"."purchase_order_region" to "authenticated";

grant insert on table "public"."purchase_order_region" to "authenticated";

grant references on table "public"."purchase_order_region" to "authenticated";

grant select on table "public"."purchase_order_region" to "authenticated";

grant trigger on table "public"."purchase_order_region" to "authenticated";

grant truncate on table "public"."purchase_order_region" to "authenticated";

grant update on table "public"."purchase_order_region" to "authenticated";

grant delete on table "public"."purchase_order_region" to "service_role";

grant insert on table "public"."purchase_order_region" to "service_role";

grant references on table "public"."purchase_order_region" to "service_role";

grant select on table "public"."purchase_order_region" to "service_role";

grant trigger on table "public"."purchase_order_region" to "service_role";

grant truncate on table "public"."purchase_order_region" to "service_role";

grant update on table "public"."purchase_order_region" to "service_role";

create policy "Allow update by creator with Finance or Super Admin role"
on "public"."budget_allocation"
as permissive
for update
to authenticated
using (((created_by = auth.uid()) AND (EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.name = ANY (ARRAY['Finance'::text, 'Super Admin'::text])))))));



