create table "public"."purchase_order_smart_status" (
    "id" bigint generated by default as identity not null,
    "purchase_order_id" bigint not null,
    "status" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX purchase_order_smart_status_pkey ON public.purchase_order_smart_status USING btree (id);

CREATE UNIQUE INDEX purchase_order_smart_status_purchase_order_id_key ON public.purchase_order_smart_status USING btree (purchase_order_id);

alter table "public"."purchase_order_smart_status" add constraint "purchase_order_smart_status_pkey" PRIMARY KEY using index "purchase_order_smart_status_pkey";

alter table "public"."purchase_order_smart_status" add constraint "purchase_order_smart_status_purchase_order_id_fkey" FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id) not valid;

alter table "public"."purchase_order_smart_status" validate constraint "purchase_order_smart_status_purchase_order_id_fkey";

alter table "public"."purchase_order_smart_status" add constraint "purchase_order_smart_status_purchase_order_id_key" UNIQUE using index "purchase_order_smart_status_purchase_order_id_key";

grant delete on table "public"."purchase_order_smart_status" to "anon";

grant insert on table "public"."purchase_order_smart_status" to "anon";

grant references on table "public"."purchase_order_smart_status" to "anon";

grant select on table "public"."purchase_order_smart_status" to "anon";

grant trigger on table "public"."purchase_order_smart_status" to "anon";

grant truncate on table "public"."purchase_order_smart_status" to "anon";

grant update on table "public"."purchase_order_smart_status" to "anon";

grant delete on table "public"."purchase_order_smart_status" to "authenticated";

grant insert on table "public"."purchase_order_smart_status" to "authenticated";

grant references on table "public"."purchase_order_smart_status" to "authenticated";

grant select on table "public"."purchase_order_smart_status" to "authenticated";

grant trigger on table "public"."purchase_order_smart_status" to "authenticated";

grant truncate on table "public"."purchase_order_smart_status" to "authenticated";

grant update on table "public"."purchase_order_smart_status" to "authenticated";

grant delete on table "public"."purchase_order_smart_status" to "service_role";

grant insert on table "public"."purchase_order_smart_status" to "service_role";

grant references on table "public"."purchase_order_smart_status" to "service_role";

grant select on table "public"."purchase_order_smart_status" to "service_role";

grant trigger on table "public"."purchase_order_smart_status" to "service_role";

grant truncate on table "public"."purchase_order_smart_status" to "service_role";

grant update on table "public"."purchase_order_smart_status" to "service_role";


