create table "public"."person" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);


CREATE UNIQUE INDEX person_pkey ON public.person USING btree (id);

alter table "public"."person" add constraint "person_pkey" PRIMARY KEY using index "person_pkey";

grant delete on table "public"."person" to "anon";

grant insert on table "public"."person" to "anon";

grant references on table "public"."person" to "anon";

grant select on table "public"."person" to "anon";

grant trigger on table "public"."person" to "anon";

grant truncate on table "public"."person" to "anon";

grant update on table "public"."person" to "anon";

grant delete on table "public"."person" to "authenticated";

grant insert on table "public"."person" to "authenticated";

grant references on table "public"."person" to "authenticated";

grant select on table "public"."person" to "authenticated";

grant trigger on table "public"."person" to "authenticated";

grant truncate on table "public"."person" to "authenticated";

grant update on table "public"."person" to "authenticated";

grant delete on table "public"."person" to "service_role";

grant insert on table "public"."person" to "service_role";

grant references on table "public"."person" to "service_role";

grant select on table "public"."person" to "service_role";

grant trigger on table "public"."person" to "service_role";

grant truncate on table "public"."person" to "service_role";

grant update on table "public"."person" to "service_role";


