create table "public"."warehouse" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "location" text not null,
    "capacity" bigint,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."warehouse" enable row level security;

CREATE UNIQUE INDEX warehouse_pkey ON public.warehouse USING btree (id);

alter table "public"."warehouse" add constraint "warehouse_pkey" PRIMARY KEY using index "warehouse_pkey";

grant delete on table "public"."warehouse" to "anon";

grant insert on table "public"."warehouse" to "anon";

grant references on table "public"."warehouse" to "anon";

grant select on table "public"."warehouse" to "anon";

grant trigger on table "public"."warehouse" to "anon";

grant truncate on table "public"."warehouse" to "anon";

grant update on table "public"."warehouse" to "anon";

grant delete on table "public"."warehouse" to "authenticated";

grant insert on table "public"."warehouse" to "authenticated";

grant references on table "public"."warehouse" to "authenticated";

grant select on table "public"."warehouse" to "authenticated";

grant trigger on table "public"."warehouse" to "authenticated";

grant truncate on table "public"."warehouse" to "authenticated";

grant update on table "public"."warehouse" to "authenticated";

grant delete on table "public"."warehouse" to "service_role";

grant insert on table "public"."warehouse" to "service_role";

grant references on table "public"."warehouse" to "service_role";

grant select on table "public"."warehouse" to "service_role";

grant trigger on table "public"."warehouse" to "service_role";

grant truncate on table "public"."warehouse" to "service_role";

grant update on table "public"."warehouse" to "service_role";
