create table "public"."purchase_order_currency" (
    "id" bigint generated by default as identity not null,
    "currency_name" text not null,
    "currency_code" text not null
);


CREATE UNIQUE INDEX purchase_order_currency_pkey ON public.purchase_order_currency USING btree (id);

alter table "public"."purchase_order_currency" add constraint "purchase_order_currency_pkey" PRIMARY KEY using index "purchase_order_currency_pkey";

grant delete on table "public"."purchase_order_currency" to "anon";

grant insert on table "public"."purchase_order_currency" to "anon";

grant references on table "public"."purchase_order_currency" to "anon";

grant select on table "public"."purchase_order_currency" to "anon";

grant trigger on table "public"."purchase_order_currency" to "anon";

grant truncate on table "public"."purchase_order_currency" to "anon";

grant update on table "public"."purchase_order_currency" to "anon";

grant delete on table "public"."purchase_order_currency" to "authenticated";

grant insert on table "public"."purchase_order_currency" to "authenticated";

grant references on table "public"."purchase_order_currency" to "authenticated";

grant select on table "public"."purchase_order_currency" to "authenticated";

grant trigger on table "public"."purchase_order_currency" to "authenticated";

grant truncate on table "public"."purchase_order_currency" to "authenticated";

grant update on table "public"."purchase_order_currency" to "authenticated";

grant delete on table "public"."purchase_order_currency" to "service_role";

grant insert on table "public"."purchase_order_currency" to "service_role";

grant references on table "public"."purchase_order_currency" to "service_role";

grant select on table "public"."purchase_order_currency" to "service_role";

grant trigger on table "public"."purchase_order_currency" to "service_role";

grant truncate on table "public"."purchase_order_currency" to "service_role";

grant update on table "public"."purchase_order_currency" to "service_role";


