create table "public"."product_price_history" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint not null,
    "old_price" numeric(10,2) not null,
    "new_price" numeric(10,2) not null,
    "reason" text,
    "updated_by" text not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
);


CREATE UNIQUE INDEX product_price_history_pkey ON public.product_price_history USING btree (id);

alter table "public"."product_price_history" add constraint "product_price_history_pkey" PRIMARY KEY using index "product_price_history_pkey";

alter table "public"."product_price_history" add constraint "product_price_history_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE not valid;

alter table "public"."product_price_history" validate constraint "product_price_history_product_id_fkey";

grant delete on table "public"."product_price_history" to "anon";

grant insert on table "public"."product_price_history" to "anon";

grant references on table "public"."product_price_history" to "anon";

grant select on table "public"."product_price_history" to "anon";

grant trigger on table "public"."product_price_history" to "anon";

grant truncate on table "public"."product_price_history" to "anon";

grant update on table "public"."product_price_history" to "anon";

grant delete on table "public"."product_price_history" to "authenticated";

grant insert on table "public"."product_price_history" to "authenticated";

grant references on table "public"."product_price_history" to "authenticated";

grant select on table "public"."product_price_history" to "authenticated";

grant trigger on table "public"."product_price_history" to "authenticated";

grant truncate on table "public"."product_price_history" to "authenticated";

grant update on table "public"."product_price_history" to "authenticated";

grant delete on table "public"."product_price_history" to "service_role";

grant insert on table "public"."product_price_history" to "service_role";

grant references on table "public"."product_price_history" to "service_role";

grant select on table "public"."product_price_history" to "service_role";

grant trigger on table "public"."product_price_history" to "service_role";

grant truncate on table "public"."product_price_history" to "service_role";

grant update on table "public"."product_price_history" to "service_role";


