create table "public"."stock_transaction_void_reason" (
    "id" bigint generated by default as identity not null,
    "reason" text,
    "voided_by" uuid,
    "stock_transaction_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."stock_transaction_void_reason" enable row level security;

alter table "public"."stock_transaction" add column "is_voided" boolean not null default false;

CREATE UNIQUE INDEX stock_transaction_void_reason_pkey ON public.stock_transaction_void_reason USING btree (id);

alter table "public"."stock_transaction_void_reason" add constraint "stock_transaction_void_reason_pkey" PRIMARY KEY using index "stock_transaction_void_reason_pkey";

alter table "public"."stock_transaction_void_reason" add constraint "stock_transaction_void_reason_voided_by_fkey" FOREIGN KEY (voided_by) REFERENCES user_profiles(id) not valid;

alter table "public"."stock_transaction_void_reason" validate constraint "stock_transaction_void_reason_voided_by_fkey";

alter table "public"."stock_transaction_void_reason" add constraint "stock_transaction_void_reason_stock_transaction_id_fkey" FOREIGN KEY (stock_transaction_id) REFERENCES stock_transaction(id) not valid;

alter table "public"."stock_transaction_void_reason" validate constraint "stock_transaction_void_reason_stock_transaction_id_fkey";

grant delete on table "public"."stock_transaction_void_reason" to "anon";

grant insert on table "public"."stock_transaction_void_reason" to "anon";

grant references on table "public"."stock_transaction_void_reason" to "anon";

grant select on table "public"."stock_transaction_void_reason" to "anon";

grant trigger on table "public"."stock_transaction_void_reason" to "anon";

grant truncate on table "public"."stock_transaction_void_reason" to "anon";

grant update on table "public"."stock_transaction_void_reason" to "anon";

grant delete on table "public"."stock_transaction_void_reason" to "authenticated";

grant insert on table "public"."stock_transaction_void_reason" to "authenticated";

grant references on table "public"."stock_transaction_void_reason" to "authenticated";

grant select on table "public"."stock_transaction_void_reason" to "authenticated";

grant trigger on table "public"."stock_transaction_void_reason" to "authenticated";

grant truncate on table "public"."stock_transaction_void_reason" to "authenticated";

grant update on table "public"."stock_transaction_void_reason" to "authenticated";

grant delete on table "public"."stock_transaction_void_reason" to "service_role";

grant insert on table "public"."stock_transaction_void_reason" to "service_role";

grant references on table "public"."stock_transaction_void_reason" to "service_role";

grant select on table "public"."stock_transaction_void_reason" to "service_role";

grant trigger on table "public"."stock_transaction_void_reason" to "service_role";

grant truncate on table "public"."stock_transaction_void_reason" to "service_role";

grant update on table "public"."stock_transaction_void_reason" to "service_role";

alter table "public"."stock_transaction_void_reason" disable row level security;