create table "public"."inventory" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint not null,
    "warehouse_id" bigint not null,
    "quantity" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


create table "public"."stock_transaction" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint not null,
    "warehouse_id" bigint not null,
    "quantity" bigint not null,
    "type" text not null,
    "destination_warehouse_id" bigint,
    "note" text,
    "created_at" timestamp with time zone not null default now(),
    "invoice_id" bigint not null
);


alter table "public"."warehouse" disable row level security;

CREATE UNIQUE INDEX inventory_pkey ON public.inventory USING btree (id);

CREATE UNIQUE INDEX stock_transaction_pkey ON public.stock_transaction USING btree (id);

alter table "public"."inventory" add constraint "inventory_pkey" PRIMARY KEY using index "inventory_pkey";

alter table "public"."stock_transaction" add constraint "stock_transaction_pkey" PRIMARY KEY using index "stock_transaction_pkey";

alter table "public"."inventory" add constraint "inventory_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) not valid;

alter table "public"."inventory" validate constraint "inventory_product_id_fkey";

alter table "public"."inventory" add constraint "inventory_warehouse_id_fkey" FOREIGN KEY (warehouse_id) REFERENCES warehouse(id) not valid;

alter table "public"."inventory" validate constraint "inventory_warehouse_id_fkey";

alter table "public"."stock_transaction" add constraint "stock_transaction_destination_warehouse_id_fkey" FOREIGN KEY (destination_warehouse_id) REFERENCES warehouse(id) not valid;

alter table "public"."stock_transaction" validate constraint "stock_transaction_destination_warehouse_id_fkey";

alter table "public"."stock_transaction" add constraint "stock_transaction_invoice_id_fkey" FOREIGN KEY (invoice_id) REFERENCES purchase_invoice(id) not valid;

alter table "public"."stock_transaction" validate constraint "stock_transaction_invoice_id_fkey";

alter table "public"."stock_transaction" add constraint "stock_transaction_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) not valid;

alter table "public"."stock_transaction" validate constraint "stock_transaction_product_id_fkey";

alter table "public"."stock_transaction" add constraint "stock_transaction_warehouse_id_fkey" FOREIGN KEY (warehouse_id) REFERENCES warehouse(id) not valid;

alter table "public"."stock_transaction" validate constraint "stock_transaction_warehouse_id_fkey";

grant delete on table "public"."inventory" to "anon";

grant insert on table "public"."inventory" to "anon";

grant references on table "public"."inventory" to "anon";

grant select on table "public"."inventory" to "anon";

grant trigger on table "public"."inventory" to "anon";

grant truncate on table "public"."inventory" to "anon";

grant update on table "public"."inventory" to "anon";

grant delete on table "public"."inventory" to "authenticated";

grant insert on table "public"."inventory" to "authenticated";

grant references on table "public"."inventory" to "authenticated";

grant select on table "public"."inventory" to "authenticated";

grant trigger on table "public"."inventory" to "authenticated";

grant truncate on table "public"."inventory" to "authenticated";

grant update on table "public"."inventory" to "authenticated";

grant delete on table "public"."inventory" to "service_role";

grant insert on table "public"."inventory" to "service_role";

grant references on table "public"."inventory" to "service_role";

grant select on table "public"."inventory" to "service_role";

grant trigger on table "public"."inventory" to "service_role";

grant truncate on table "public"."inventory" to "service_role";

grant update on table "public"."inventory" to "service_role";

grant delete on table "public"."stock_transaction" to "anon";

grant insert on table "public"."stock_transaction" to "anon";

grant references on table "public"."stock_transaction" to "anon";

grant select on table "public"."stock_transaction" to "anon";

grant trigger on table "public"."stock_transaction" to "anon";

grant truncate on table "public"."stock_transaction" to "anon";

grant update on table "public"."stock_transaction" to "anon";

grant delete on table "public"."stock_transaction" to "authenticated";

grant insert on table "public"."stock_transaction" to "authenticated";

grant references on table "public"."stock_transaction" to "authenticated";

grant select on table "public"."stock_transaction" to "authenticated";

grant trigger on table "public"."stock_transaction" to "authenticated";

grant truncate on table "public"."stock_transaction" to "authenticated";

grant update on table "public"."stock_transaction" to "authenticated";

grant delete on table "public"."stock_transaction" to "service_role";

grant insert on table "public"."stock_transaction" to "service_role";

grant references on table "public"."stock_transaction" to "service_role";

grant select on table "public"."stock_transaction" to "service_role";

grant trigger on table "public"."stock_transaction" to "service_role";

grant truncate on table "public"."stock_transaction" to "service_role";

grant update on table "public"."stock_transaction" to "service_role";
