create table "public"."budget_allocations" (
    "id" bigint generated by default as identity not null,
    "budget_id" bigint not null,
    "amount" numeric(14,2) not null default 0,
    "amount_usd" numeric(14,2) generated always as ((amount / NULLIF(exchange_rate_usd, (0)::numeric))) stored,
    "exchange_rate_usd" numeric(10,4) not null default 1,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
);


create table "public"."budget_invoices" (
    "id" bigint generated by default as identity not null,
    "budget_id" bigint not null,
    "amount" numeric(14,2) not null default 0,
    "amount_usd" numeric(14,2) generated always as ((amount / NULLIF(exchange_rate_usd, (0)::numeric))) stored,
    "exchange_rate_usd" numeric(10,4) not null default 1,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
);


alter table "public"."budget_audit_logs" alter column "created_at" set default now();

alter table "public"."budget_audit_logs" alter column "created_at" drop not null;

alter table "public"."budgets" alter column "created_at" set default now();

alter table "public"."budgets" alter column "created_at" drop not null;

alter table "public"."budgets" alter column "updated_at" set default now();

alter table "public"."budgets" alter column "updated_at" drop not null;

CREATE UNIQUE INDEX budget_allocations_pkey ON public.budget_allocations USING btree (id);

CREATE UNIQUE INDEX budget_invoices_pkey ON public.budget_invoices USING btree (id);

alter table "public"."budget_allocations" add constraint "budget_allocations_pkey" PRIMARY KEY using index "budget_allocations_pkey";

alter table "public"."budget_invoices" add constraint "budget_invoices_pkey" PRIMARY KEY using index "budget_invoices_pkey";

alter table "public"."budget_allocations" add constraint "budget_allocations_budget_id_fkey" FOREIGN KEY (budget_id) REFERENCES budgets(id) ON DELETE CASCADE not valid;

alter table "public"."budget_allocations" validate constraint "budget_allocations_budget_id_fkey";

alter table "public"."budget_invoices" add constraint "budget_invoices_budget_id_fkey" FOREIGN KEY (budget_id) REFERENCES budgets(id) ON DELETE CASCADE not valid;

alter table "public"."budget_invoices" validate constraint "budget_invoices_budget_id_fkey";

grant delete on table "public"."budget_allocations" to "anon";

grant insert on table "public"."budget_allocations" to "anon";

grant references on table "public"."budget_allocations" to "anon";

grant select on table "public"."budget_allocations" to "anon";

grant trigger on table "public"."budget_allocations" to "anon";

grant truncate on table "public"."budget_allocations" to "anon";

grant update on table "public"."budget_allocations" to "anon";

grant delete on table "public"."budget_allocations" to "authenticated";

grant insert on table "public"."budget_allocations" to "authenticated";

grant references on table "public"."budget_allocations" to "authenticated";

grant select on table "public"."budget_allocations" to "authenticated";

grant trigger on table "public"."budget_allocations" to "authenticated";

grant truncate on table "public"."budget_allocations" to "authenticated";

grant update on table "public"."budget_allocations" to "authenticated";

grant delete on table "public"."budget_allocations" to "service_role";

grant insert on table "public"."budget_allocations" to "service_role";

grant references on table "public"."budget_allocations" to "service_role";

grant select on table "public"."budget_allocations" to "service_role";

grant trigger on table "public"."budget_allocations" to "service_role";

grant truncate on table "public"."budget_allocations" to "service_role";

grant update on table "public"."budget_allocations" to "service_role";

grant delete on table "public"."budget_invoices" to "anon";

grant insert on table "public"."budget_invoices" to "anon";

grant references on table "public"."budget_invoices" to "anon";

grant select on table "public"."budget_invoices" to "anon";

grant trigger on table "public"."budget_invoices" to "anon";

grant truncate on table "public"."budget_invoices" to "anon";

grant update on table "public"."budget_invoices" to "anon";

grant delete on table "public"."budget_invoices" to "authenticated";

grant insert on table "public"."budget_invoices" to "authenticated";

grant references on table "public"."budget_invoices" to "authenticated";

grant select on table "public"."budget_invoices" to "authenticated";

grant trigger on table "public"."budget_invoices" to "authenticated";

grant truncate on table "public"."budget_invoices" to "authenticated";

grant update on table "public"."budget_invoices" to "authenticated";

grant delete on table "public"."budget_invoices" to "service_role";

grant insert on table "public"."budget_invoices" to "service_role";

grant references on table "public"."budget_invoices" to "service_role";

grant select on table "public"."budget_invoices" to "service_role";

grant trigger on table "public"."budget_invoices" to "service_role";

grant truncate on table "public"."budget_invoices" to "service_role";

grant update on table "public"."budget_invoices" to "service_role";


