create table "public"."product_alias" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "type_id" bigint,
    "language_id" bigint,
    "product_id" bigint not null
);


alter table "public"."product_alias" disable row level security;

create table "public"."product_alias_language" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."product_alias_language" disable row level security;

create table "public"."product_alias_type" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now()
);

CREATE UNIQUE INDEX product_alias_name_key ON public.product_alias USING btree (name);

alter table "public"."product_alias" add constraint "product_alias_name_key" UNIQUE using index "product_alias_name_key";


alter table "public"."product_alias_type" disable row level security;

CREATE UNIQUE INDEX product_alias_language_pkey ON public.product_alias_language USING btree (id);

CREATE UNIQUE INDEX product_alias_pkey ON public.product_alias USING btree (id);

CREATE UNIQUE INDEX product_alias_type_pkey ON public.product_alias_type USING btree (id);

alter table "public"."product_alias" add constraint "product_alias_pkey" PRIMARY KEY using index "product_alias_pkey";

alter table "public"."product_alias_language" add constraint "product_alias_language_pkey" PRIMARY KEY using index "product_alias_language_pkey";

alter table "public"."product_alias_type" add constraint "product_alias_type_pkey" PRIMARY KEY using index "product_alias_type_pkey";

alter table "public"."product_alias" add constraint "product_alias_language_id_fkey" FOREIGN KEY (language_id) REFERENCES product_alias_language(id) not valid;

alter table "public"."product_alias" validate constraint "product_alias_language_id_fkey";

alter table "public"."product_alias" add constraint "product_alias_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) not valid;

alter table "public"."product_alias" validate constraint "product_alias_product_id_fkey";

alter table "public"."product_alias" add constraint "product_alias_type_id_fkey" FOREIGN KEY (type_id) REFERENCES product_alias_type(id) not valid;

alter table "public"."product_alias" validate constraint "product_alias_type_id_fkey";

grant delete on table "public"."product_alias" to "anon";

grant insert on table "public"."product_alias" to "anon";

grant references on table "public"."product_alias" to "anon";

grant select on table "public"."product_alias" to "anon";

grant trigger on table "public"."product_alias" to "anon";

grant truncate on table "public"."product_alias" to "anon";

grant update on table "public"."product_alias" to "anon";

grant delete on table "public"."product_alias" to "authenticated";

grant insert on table "public"."product_alias" to "authenticated";

grant references on table "public"."product_alias" to "authenticated";

grant select on table "public"."product_alias" to "authenticated";

grant trigger on table "public"."product_alias" to "authenticated";

grant truncate on table "public"."product_alias" to "authenticated";

grant update on table "public"."product_alias" to "authenticated";

grant delete on table "public"."product_alias" to "service_role";

grant insert on table "public"."product_alias" to "service_role";

grant references on table "public"."product_alias" to "service_role";

grant select on table "public"."product_alias" to "service_role";

grant trigger on table "public"."product_alias" to "service_role";

grant truncate on table "public"."product_alias" to "service_role";

grant update on table "public"."product_alias" to "service_role";

grant delete on table "public"."product_alias_language" to "anon";

grant insert on table "public"."product_alias_language" to "anon";

grant references on table "public"."product_alias_language" to "anon";

grant select on table "public"."product_alias_language" to "anon";

grant trigger on table "public"."product_alias_language" to "anon";

grant truncate on table "public"."product_alias_language" to "anon";

grant update on table "public"."product_alias_language" to "anon";

grant delete on table "public"."product_alias_language" to "authenticated";

grant insert on table "public"."product_alias_language" to "authenticated";

grant references on table "public"."product_alias_language" to "authenticated";

grant select on table "public"."product_alias_language" to "authenticated";

grant trigger on table "public"."product_alias_language" to "authenticated";

grant truncate on table "public"."product_alias_language" to "authenticated";

grant update on table "public"."product_alias_language" to "authenticated";

grant delete on table "public"."product_alias_language" to "service_role";

grant insert on table "public"."product_alias_language" to "service_role";

grant references on table "public"."product_alias_language" to "service_role";

grant select on table "public"."product_alias_language" to "service_role";

grant trigger on table "public"."product_alias_language" to "service_role";

grant truncate on table "public"."product_alias_language" to "service_role";

grant update on table "public"."product_alias_language" to "service_role";

grant delete on table "public"."product_alias_type" to "anon";

grant insert on table "public"."product_alias_type" to "anon";

grant references on table "public"."product_alias_type" to "anon";

grant select on table "public"."product_alias_type" to "anon";

grant trigger on table "public"."product_alias_type" to "anon";

grant truncate on table "public"."product_alias_type" to "anon";

grant update on table "public"."product_alias_type" to "anon";

grant delete on table "public"."product_alias_type" to "authenticated";

grant insert on table "public"."product_alias_type" to "authenticated";

grant references on table "public"."product_alias_type" to "authenticated";

grant select on table "public"."product_alias_type" to "authenticated";

grant trigger on table "public"."product_alias_type" to "authenticated";

grant truncate on table "public"."product_alias_type" to "authenticated";

grant update on table "public"."product_alias_type" to "authenticated";

grant delete on table "public"."product_alias_type" to "service_role";

grant insert on table "public"."product_alias_type" to "service_role";

grant references on table "public"."product_alias_type" to "service_role";

grant select on table "public"."product_alias_type" to "service_role";

grant trigger on table "public"."product_alias_type" to "service_role";

grant truncate on table "public"."product_alias_type" to "service_role";

grant update on table "public"."product_alias_type" to "service_role";


