create table "public"."budget_allocation_activity_logs" (
    "id" bigint generated by default as identity not null,
    "allocation_id" bigint,
    "po_id" bigint,
    "user_id" uuid not null,
    "role" text not null,
    "action_type" text,
    "amount" numeric,
    "currency_code" text not null,
    "notes" text,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now())
);


CREATE UNIQUE INDEX budget_allocation_activity_logs_pkey ON public.budget_allocation_activity_logs USING btree (id);

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_pkey" PRIMARY KEY using index "budget_allocation_activity_logs_pkey";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_action_type_check" CHECK ((action_type = ANY (ARRAY['Create'::text, 'Cancel'::text, 'Update'::text]))) not valid;

alter table "public"."budget_allocation_activity_logs" validate constraint "budget_allocation_activity_logs_action_type_check";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_allocation_id_fkey" FOREIGN KEY (allocation_id) REFERENCES budget_allocation(id) not valid;

alter table "public"."budget_allocation_activity_logs" validate constraint "budget_allocation_activity_logs_allocation_id_fkey";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_po_id_fkey" FOREIGN KEY (po_id) REFERENCES purchase_order(id) not valid;

alter table "public"."budget_allocation_activity_logs" validate constraint "budget_allocation_activity_logs_po_id_fkey";

alter table "public"."budget_allocation_activity_logs" add constraint "budget_allocation_activity_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."budget_allocation_activity_logs" validate constraint "budget_allocation_activity_logs_user_id_fkey";

grant delete on table "public"."budget_allocation_activity_logs" to "anon";

grant insert on table "public"."budget_allocation_activity_logs" to "anon";

grant references on table "public"."budget_allocation_activity_logs" to "anon";

grant select on table "public"."budget_allocation_activity_logs" to "anon";

grant trigger on table "public"."budget_allocation_activity_logs" to "anon";

grant truncate on table "public"."budget_allocation_activity_logs" to "anon";

grant update on table "public"."budget_allocation_activity_logs" to "anon";

grant delete on table "public"."budget_allocation_activity_logs" to "authenticated";

grant insert on table "public"."budget_allocation_activity_logs" to "authenticated";

grant references on table "public"."budget_allocation_activity_logs" to "authenticated";

grant select on table "public"."budget_allocation_activity_logs" to "authenticated";

grant trigger on table "public"."budget_allocation_activity_logs" to "authenticated";

grant truncate on table "public"."budget_allocation_activity_logs" to "authenticated";

grant update on table "public"."budget_allocation_activity_logs" to "authenticated";

grant delete on table "public"."budget_allocation_activity_logs" to "service_role";

grant insert on table "public"."budget_allocation_activity_logs" to "service_role";

grant references on table "public"."budget_allocation_activity_logs" to "service_role";

grant select on table "public"."budget_allocation_activity_logs" to "service_role";

grant trigger on table "public"."budget_allocation_activity_logs" to "service_role";

grant truncate on table "public"."budget_allocation_activity_logs" to "service_role";

grant update on table "public"."budget_allocation_activity_logs" to "service_role";


