create table "public"."supplier_audit_log" (
    "id" bigint generated by default as identity not null,
    "supplier_id" bigint not null,
    "changed_by" uuid,
    "changed_field" text,
    "old_values" text,
    "new_values" text,
    "changed_at" timestamp with time zone default timezone('utc'::text, now())
);


CREATE UNIQUE INDEX supplier_audit_log_pkey ON public.supplier_audit_log USING btree (id);

alter table "public"."supplier_audit_log" add constraint "supplier_audit_log_pkey" PRIMARY KEY using index "supplier_audit_log_pkey";

alter table "public"."supplier_audit_log" add constraint "supplier_audit_log_changed_by_fkey" FOREIGN KEY (changed_by) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."supplier_audit_log" validate constraint "supplier_audit_log_changed_by_fkey";

alter table "public"."supplier_audit_log" add constraint "supplier_audit_log_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE CASCADE not valid;

alter table "public"."supplier_audit_log" validate constraint "supplier_audit_log_supplier_id_fkey";

grant delete on table "public"."supplier_audit_log" to "anon";

grant insert on table "public"."supplier_audit_log" to "anon";

grant references on table "public"."supplier_audit_log" to "anon";

grant select on table "public"."supplier_audit_log" to "anon";

grant trigger on table "public"."supplier_audit_log" to "anon";

grant truncate on table "public"."supplier_audit_log" to "anon";

grant update on table "public"."supplier_audit_log" to "anon";

grant delete on table "public"."supplier_audit_log" to "authenticated";

grant insert on table "public"."supplier_audit_log" to "authenticated";

grant references on table "public"."supplier_audit_log" to "authenticated";

grant select on table "public"."supplier_audit_log" to "authenticated";

grant trigger on table "public"."supplier_audit_log" to "authenticated";

grant truncate on table "public"."supplier_audit_log" to "authenticated";

grant update on table "public"."supplier_audit_log" to "authenticated";

grant delete on table "public"."supplier_audit_log" to "service_role";

grant insert on table "public"."supplier_audit_log" to "service_role";

grant references on table "public"."supplier_audit_log" to "service_role";

grant select on table "public"."supplier_audit_log" to "service_role";

grant trigger on table "public"."supplier_audit_log" to "service_role";

grant truncate on table "public"."supplier_audit_log" to "service_role";

grant update on table "public"."supplier_audit_log" to "service_role";


