create table "public"."purchase_invoice" (
    "id" bigint generated by default as identity not null,
    "purchase_invoice_number" text not null,
    "invoice_date" date not null,
    "due_date" date not null,
    "currency_id" bigint not null,
    "exchange_rate_to_usd" double precision not null,
    "purchase_order_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "status" text not null default 'Pending'::text,
    "note" text
);


alter table "public"."purchase_invoice" enable row level security;

create table "public"."purchase_invoice_item" (
    "id" bigint generated by default as identity not null,
    "purchase_invoice_id" bigint not null,
    "purchase_order_id" bigint not null,
    "product_id" bigint not null,
    "quantity" bigint not null,
    "unit_price_local" double precision not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."purchase_invoice_item" enable row level security;

create table "public"."purchase_order_update_reason" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "purchase_order_id" bigint not null,
    "reason" text not null,
    "action" text not null
);


alter table "public"."purchase_order_update_reason" enable row level security;

CREATE UNIQUE INDEX purchase_invoice_item_pkey ON public.purchase_invoice_item USING btree (id);

CREATE UNIQUE INDEX purchase_invoice_pkey ON public.purchase_invoice USING btree (id);

CREATE UNIQUE INDEX purchase_invoice_purchase_invoice_number_key ON public.purchase_invoice USING btree (purchase_invoice_number);

CREATE UNIQUE INDEX purchase_order_update_reason_pkey ON public.purchase_order_update_reason USING btree (id);

alter table "public"."purchase_invoice" add constraint "purchase_invoice_pkey" PRIMARY KEY using index "purchase_invoice_pkey";

alter table "public"."purchase_invoice_item" add constraint "purchase_invoice_item_pkey" PRIMARY KEY using index "purchase_invoice_item_pkey";

alter table "public"."purchase_order_update_reason" add constraint "purchase_order_update_reason_pkey" PRIMARY KEY using index "purchase_order_update_reason_pkey";

alter table "public"."purchase_invoice" add constraint "purchase_invoice_currency_id_fkey" FOREIGN KEY (currency_id) REFERENCES product_currency(id) not valid;

alter table "public"."purchase_invoice" validate constraint "purchase_invoice_currency_id_fkey";

alter table "public"."purchase_invoice" add constraint "purchase_invoice_purchase_invoice_number_key" UNIQUE using index "purchase_invoice_purchase_invoice_number_key";

alter table "public"."purchase_invoice" add constraint "purchase_invoice_purchase_order_id_fkey" FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id) not valid;

alter table "public"."purchase_invoice" validate constraint "purchase_invoice_purchase_order_id_fkey";

alter table "public"."purchase_invoice_item" add constraint "purchase_invoice_item_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) not valid;

alter table "public"."purchase_invoice_item" validate constraint "purchase_invoice_item_product_id_fkey";

alter table "public"."purchase_invoice_item" add constraint "purchase_invoice_item_purchase_invoice_id_fkey" FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoice(id) not valid;

alter table "public"."purchase_invoice_item" validate constraint "purchase_invoice_item_purchase_invoice_id_fkey";

alter table "public"."purchase_invoice_item" add constraint "purchase_invoice_item_purchase_order_id_fkey" FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id) not valid;

alter table "public"."purchase_invoice_item" validate constraint "purchase_invoice_item_purchase_order_id_fkey";

alter table "public"."purchase_order_update_reason" add constraint "purchase_order_update_reason_purchase_order_id_fkey" FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."purchase_order_update_reason" validate constraint "purchase_order_update_reason_purchase_order_id_fkey";

grant delete on table "public"."purchase_invoice" to "anon";

grant insert on table "public"."purchase_invoice" to "anon";

grant references on table "public"."purchase_invoice" to "anon";

grant select on table "public"."purchase_invoice" to "anon";

grant trigger on table "public"."purchase_invoice" to "anon";

grant truncate on table "public"."purchase_invoice" to "anon";

grant update on table "public"."purchase_invoice" to "anon";

grant delete on table "public"."purchase_invoice" to "authenticated";

grant insert on table "public"."purchase_invoice" to "authenticated";

grant references on table "public"."purchase_invoice" to "authenticated";

grant select on table "public"."purchase_invoice" to "authenticated";

grant trigger on table "public"."purchase_invoice" to "authenticated";

grant truncate on table "public"."purchase_invoice" to "authenticated";

grant update on table "public"."purchase_invoice" to "authenticated";

grant delete on table "public"."purchase_invoice" to "service_role";

grant insert on table "public"."purchase_invoice" to "service_role";

grant references on table "public"."purchase_invoice" to "service_role";

grant select on table "public"."purchase_invoice" to "service_role";

grant trigger on table "public"."purchase_invoice" to "service_role";

grant truncate on table "public"."purchase_invoice" to "service_role";

grant update on table "public"."purchase_invoice" to "service_role";

grant delete on table "public"."purchase_invoice_item" to "anon";

grant insert on table "public"."purchase_invoice_item" to "anon";

grant references on table "public"."purchase_invoice_item" to "anon";

grant select on table "public"."purchase_invoice_item" to "anon";

grant trigger on table "public"."purchase_invoice_item" to "anon";

grant truncate on table "public"."purchase_invoice_item" to "anon";

grant update on table "public"."purchase_invoice_item" to "anon";

grant delete on table "public"."purchase_invoice_item" to "authenticated";

grant insert on table "public"."purchase_invoice_item" to "authenticated";

grant references on table "public"."purchase_invoice_item" to "authenticated";

grant select on table "public"."purchase_invoice_item" to "authenticated";

grant trigger on table "public"."purchase_invoice_item" to "authenticated";

grant truncate on table "public"."purchase_invoice_item" to "authenticated";

grant update on table "public"."purchase_invoice_item" to "authenticated";

grant delete on table "public"."purchase_invoice_item" to "service_role";

grant insert on table "public"."purchase_invoice_item" to "service_role";

grant references on table "public"."purchase_invoice_item" to "service_role";

grant select on table "public"."purchase_invoice_item" to "service_role";

grant trigger on table "public"."purchase_invoice_item" to "service_role";

grant truncate on table "public"."purchase_invoice_item" to "service_role";

grant update on table "public"."purchase_invoice_item" to "service_role";

grant delete on table "public"."purchase_order_update_reason" to "anon";

grant insert on table "public"."purchase_order_update_reason" to "anon";

grant references on table "public"."purchase_order_update_reason" to "anon";

grant select on table "public"."purchase_order_update_reason" to "anon";

grant trigger on table "public"."purchase_order_update_reason" to "anon";

grant truncate on table "public"."purchase_order_update_reason" to "anon";

grant update on table "public"."purchase_order_update_reason" to "anon";

grant delete on table "public"."purchase_order_update_reason" to "authenticated";

grant insert on table "public"."purchase_order_update_reason" to "authenticated";

grant references on table "public"."purchase_order_update_reason" to "authenticated";

grant select on table "public"."purchase_order_update_reason" to "authenticated";

grant trigger on table "public"."purchase_order_update_reason" to "authenticated";

grant truncate on table "public"."purchase_order_update_reason" to "authenticated";

grant update on table "public"."purchase_order_update_reason" to "authenticated";

grant delete on table "public"."purchase_order_update_reason" to "service_role";

grant insert on table "public"."purchase_order_update_reason" to "service_role";

grant references on table "public"."purchase_order_update_reason" to "service_role";

grant select on table "public"."purchase_order_update_reason" to "service_role";

grant trigger on table "public"."purchase_order_update_reason" to "service_role";

grant truncate on table "public"."purchase_order_update_reason" to "service_role";

grant update on table "public"."purchase_order_update_reason" to "service_role";


