  create table "public"."product_audit_log" (
    "id" bigint generated by default as identity not null,
    "product_id" bigint,
    "changed_by" uuid,
    "changed_field" text,
    "old_values" text,
    "new_values" text,
    "changed_at" timestamp with time zone default timezone('utc'::text, now()),
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."product_audit_log" enable row level security;

CREATE UNIQUE INDEX product_audit_log_pkey ON public.product_audit_log USING btree (id);

alter table "public"."product_audit_log" add constraint "product_audit_log_pkey" PRIMARY KEY using index "product_audit_log_pkey";

alter table "public"."product_audit_log" add constraint "product_audit_log_changed_by_fkey" FOREIGN KEY (changed_by) REFERENCES user_profiles(id) not valid;

alter table "public"."product_audit_log" validate constraint "product_audit_log_changed_by_fkey";

alter table "public"."product_audit_log" add constraint "product_audit_log_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product(id) not valid;

alter table "public"."product_audit_log" validate constraint "product_audit_log_product_id_fkey";

grant delete on table "public"."product_audit_log" to "anon";

grant insert on table "public"."product_audit_log" to "anon";

grant references on table "public"."product_audit_log" to "anon";

grant select on table "public"."product_audit_log" to "anon";

grant trigger on table "public"."product_audit_log" to "anon";

grant truncate on table "public"."product_audit_log" to "anon";

grant update on table "public"."product_audit_log" to "anon";

grant delete on table "public"."product_audit_log" to "authenticated";

grant insert on table "public"."product_audit_log" to "authenticated";

grant references on table "public"."product_audit_log" to "authenticated";

grant select on table "public"."product_audit_log" to "authenticated";

grant trigger on table "public"."product_audit_log" to "authenticated";

grant truncate on table "public"."product_audit_log" to "authenticated";

grant update on table "public"."product_audit_log" to "authenticated";

grant delete on table "public"."product_audit_log" to "service_role";

grant insert on table "public"."product_audit_log" to "service_role";

grant references on table "public"."product_audit_log" to "service_role";

grant select on table "public"."product_audit_log" to "service_role";

grant trigger on table "public"."product_audit_log" to "service_role";

grant truncate on table "public"."product_audit_log" to "service_role";

grant update on table "public"."product_audit_log" to "service_role";

alter table "public"."product_audit_log" disable row level security;