create table "public"."product_currency" (
    "id" bigint generated by default as identity not null,
    "currency_code" character varying(10) not null,
    "currency_name" character varying(50) not null,
    "is_active" boolean default true,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);


CREATE UNIQUE INDEX product_currency_currency_name_key ON public.product_currency USING btree (currency_name);

CREATE UNIQUE INDEX currency_currency_code_key ON public.product_currency USING btree (currency_code);

CREATE UNIQUE INDEX currency_pkey ON public.product_currency USING btree (id);

alter table "public"."product_currency" add constraint "currency_pkey" PRIMARY KEY using index "currency_pkey";

alter table "public"."product_currency" add constraint "currency_currency_code_key" UNIQUE using index "currency_currency_code_key";

alter table "public"."product_currency" add constraint "product_currency_currency_name_key" UNIQUE using index "product_currency_currency_name_key";

alter table "public"."product_currency" add constraint "product_currency_id_fkey" FOREIGN KEY (id) REFERENCES product(id) not valid;

alter table "public"."product_currency" validate constraint "product_currency_id_fkey";

grant delete on table "public"."product_currency" to "anon";

grant insert on table "public"."product_currency" to "anon";

grant references on table "public"."product_currency" to "anon";

grant select on table "public"."product_currency" to "anon";

grant trigger on table "public"."product_currency" to "anon";

grant truncate on table "public"."product_currency" to "anon";

grant update on table "public"."product_currency" to "anon";

grant delete on table "public"."product_currency" to "authenticated";

grant insert on table "public"."product_currency" to "authenticated";

grant references on table "public"."product_currency" to "authenticated";

grant select on table "public"."product_currency" to "authenticated";

grant trigger on table "public"."product_currency" to "authenticated";

grant truncate on table "public"."product_currency" to "authenticated";

grant update on table "public"."product_currency" to "authenticated";

grant delete on table "public"."product_currency" to "service_role";

grant insert on table "public"."product_currency" to "service_role";

grant references on table "public"."product_currency" to "service_role";

grant select on table "public"."product_currency" to "service_role";

grant trigger on table "public"."product_currency" to "service_role";

grant truncate on table "public"."product_currency" to "service_role";

grant update on table "public"."product_currency" to "service_role";


