create table "public"."person_rank" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."person_rank" enable row level security;

alter table "public"."person" drop column "rank";

alter table "public"."person" add column "rank_id" bigint;

CREATE UNIQUE INDEX person_rank_pkey ON public.person_rank USING btree (id);

alter table "public"."person_rank" add constraint "person_rank_pkey" PRIMARY KEY using index "person_rank_pkey";

alter table "public"."person" add constraint "person_rank_id_fkey" FOREIGN KEY (rank_id) REFERENCES person_rank(id) not valid;

alter table "public"."person" validate constraint "person_rank_id_fkey";

grant delete on table "public"."person_rank" to "anon";

grant insert on table "public"."person_rank" to "anon";

grant references on table "public"."person_rank" to "anon";

grant select on table "public"."person_rank" to "anon";

grant trigger on table "public"."person_rank" to "anon";

grant truncate on table "public"."person_rank" to "anon";

grant update on table "public"."person_rank" to "anon";

grant delete on table "public"."person_rank" to "authenticated";

grant insert on table "public"."person_rank" to "authenticated";

grant references on table "public"."person_rank" to "authenticated";

grant select on table "public"."person_rank" to "authenticated";

grant trigger on table "public"."person_rank" to "authenticated";

grant truncate on table "public"."person_rank" to "authenticated";

grant update on table "public"."person_rank" to "authenticated";

grant delete on table "public"."person_rank" to "service_role";

grant insert on table "public"."person_rank" to "service_role";

grant references on table "public"."person_rank" to "service_role";

grant select on table "public"."person_rank" to "service_role";

grant trigger on table "public"."person_rank" to "service_role";

grant truncate on table "public"."person_rank" to "service_role";

grant update on table "public"."person_rank" to "service_role";

alter table "public"."person_rank" disable row level security;
