create table "public"."supplier" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "contact_person" text not null,
    "email" text not null,
    "phone" text,
    "address" text,
    "status" boolean not null default true,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now())
);


create table "public"."table_name" (
    "id" bigint generated by default as identity not null,
    "inserted_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "data" jsonb,
    "name" text
);


CREATE UNIQUE INDEX supplier_email_key ON public.supplier USING btree (email);

CREATE UNIQUE INDEX supplier_pkey ON public.supplier USING btree (id);

CREATE UNIQUE INDEX table_name_pkey ON public.table_name USING btree (id);

alter table "public"."supplier" add constraint "supplier_pkey" PRIMARY KEY using index "supplier_pkey";

alter table "public"."table_name" add constraint "table_name_pkey" PRIMARY KEY using index "table_name_pkey";

alter table "public"."supplier" add constraint "supplier_email_check" CHECK ((email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'::text)) not valid;

alter table "public"."supplier" validate constraint "supplier_email_check";

alter table "public"."supplier" add constraint "supplier_email_key" UNIQUE using index "supplier_email_key";

grant delete on table "public"."supplier" to "anon";

grant insert on table "public"."supplier" to "anon";

grant references on table "public"."supplier" to "anon";

grant select on table "public"."supplier" to "anon";

grant trigger on table "public"."supplier" to "anon";

grant truncate on table "public"."supplier" to "anon";

grant update on table "public"."supplier" to "anon";

grant delete on table "public"."supplier" to "authenticated";

grant insert on table "public"."supplier" to "authenticated";

grant references on table "public"."supplier" to "authenticated";

grant select on table "public"."supplier" to "authenticated";

grant trigger on table "public"."supplier" to "authenticated";

grant truncate on table "public"."supplier" to "authenticated";

grant update on table "public"."supplier" to "authenticated";

grant delete on table "public"."supplier" to "service_role";

grant insert on table "public"."supplier" to "service_role";

grant references on table "public"."supplier" to "service_role";

grant select on table "public"."supplier" to "service_role";

grant trigger on table "public"."supplier" to "service_role";

grant truncate on table "public"."supplier" to "service_role";

grant update on table "public"."supplier" to "service_role";

grant delete on table "public"."table_name" to "anon";

grant insert on table "public"."table_name" to "anon";

grant references on table "public"."table_name" to "anon";

grant select on table "public"."table_name" to "anon";

grant trigger on table "public"."table_name" to "anon";

grant truncate on table "public"."table_name" to "anon";

grant update on table "public"."table_name" to "anon";

grant delete on table "public"."table_name" to "authenticated";

grant insert on table "public"."table_name" to "authenticated";

grant references on table "public"."table_name" to "authenticated";

grant select on table "public"."table_name" to "authenticated";

grant trigger on table "public"."table_name" to "authenticated";

grant truncate on table "public"."table_name" to "authenticated";

grant update on table "public"."table_name" to "authenticated";

grant delete on table "public"."table_name" to "service_role";

grant insert on table "public"."table_name" to "service_role";

grant references on table "public"."table_name" to "service_role";

grant select on table "public"."table_name" to "service_role";

grant trigger on table "public"."table_name" to "service_role";

grant truncate on table "public"."table_name" to "service_role";

grant update on table "public"."table_name" to "service_role";


