create table "public"."purchase_order_region" (
    "id" bigint generated by default as identity not null,
    "name" text not null
);


CREATE UNIQUE INDEX purchase_order_region_pkey ON public.purchase_order_region USING btree (id);

alter table "public"."purchase_order_region" add constraint "purchase_order_region_pkey" PRIMARY KEY using index "purchase_order_region_pkey";

grant delete on table "public"."purchase_order_region" to "anon";

grant insert on table "public"."purchase_order_region" to "anon";

grant references on table "public"."purchase_order_region" to "anon";

grant select on table "public"."purchase_order_region" to "anon";

grant trigger on table "public"."purchase_order_region" to "anon";

grant truncate on table "public"."purchase_order_region" to "anon";

grant update on table "public"."purchase_order_region" to "anon";

grant delete on table "public"."purchase_order_region" to "authenticated";

grant insert on table "public"."purchase_order_region" to "authenticated";

grant references on table "public"."purchase_order_region" to "authenticated";

grant select on table "public"."purchase_order_region" to "authenticated";

grant trigger on table "public"."purchase_order_region" to "authenticated";

grant truncate on table "public"."purchase_order_region" to "authenticated";

grant update on table "public"."purchase_order_region" to "authenticated";

grant delete on table "public"."purchase_order_region" to "service_role";

grant insert on table "public"."purchase_order_region" to "service_role";

grant references on table "public"."purchase_order_region" to "service_role";

grant select on table "public"."purchase_order_region" to "service_role";

grant trigger on table "public"."purchase_order_region" to "service_role";

grant truncate on table "public"."purchase_order_region" to "service_role";

grant update on table "public"."purchase_order_region" to "service_role";


