create table "public"."user_audit_log" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "actor" text not null,
    "target" text not null,
    "target_id" uuid not null,
    "changed_set" jsonb,
    "ip_address" text,
    "device" text,
    "location" text
);


CREATE UNIQUE INDEX user_audit_log_pkey ON public.user_audit_log USING btree (id);

CREATE UNIQUE INDEX user_audit_log_target_id_key ON public.user_audit_log USING btree (target_id);

alter table "public"."user_audit_log" add constraint "user_audit_log_pkey" PRIMARY KEY using index "user_audit_log_pkey";

alter table "public"."user_audit_log" add constraint "user_audit_log_target_id_key" UNIQUE using index "user_audit_log_target_id_key";

grant delete on table "public"."user_audit_log" to "anon";

grant insert on table "public"."user_audit_log" to "anon";

grant references on table "public"."user_audit_log" to "anon";

grant select on table "public"."user_audit_log" to "anon";

grant trigger on table "public"."user_audit_log" to "anon";

grant truncate on table "public"."user_audit_log" to "anon";

grant update on table "public"."user_audit_log" to "anon";

grant delete on table "public"."user_audit_log" to "authenticated";

grant insert on table "public"."user_audit_log" to "authenticated";

grant references on table "public"."user_audit_log" to "authenticated";

grant select on table "public"."user_audit_log" to "authenticated";

grant trigger on table "public"."user_audit_log" to "authenticated";

grant truncate on table "public"."user_audit_log" to "authenticated";

grant update on table "public"."user_audit_log" to "authenticated";

grant delete on table "public"."user_audit_log" to "service_role";

grant insert on table "public"."user_audit_log" to "service_role";

grant references on table "public"."user_audit_log" to "service_role";

grant select on table "public"."user_audit_log" to "service_role";

grant trigger on table "public"."user_audit_log" to "service_role";

grant truncate on table "public"."user_audit_log" to "service_role";

grant update on table "public"."user_audit_log" to "service_role";


