create table "public"."purchase_order_drafts" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "po_number" text,
    "supplier_id" bigint,
    "region_id" bigint,
    "budget_id" integer,
    "order_date" date,
    "currency_id" bigint,
    "usd_exchange_rate" numeric(12,6),
    "contact_person_id" bigint,
    "sign_person_id" bigint,
    "authorized_signer_id" bigint,
    "expected_delivery_date" date,
    "note" text,
    "form_data" jsonb not null default '{}'::jsonb,
    "current_step" integer not null default 0,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);

CREATE UNIQUE INDEX purchase_order_drafts_pkey ON public.purchase_order_drafts USING btree (id);

CREATE INDEX purchase_order_drafts_user_id_idx ON public.purchase_order_drafts USING btree (user_id);

CREATE INDEX purchase_order_drafts_created_at_idx ON public.purchase_order_drafts USING btree (created_at);

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_pkey" PRIMARY KEY using index "purchase_order_drafts_pkey";

-- Foreign key constraints (optional since these are drafts and might not have complete data)
alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES supplier(id) ON DELETE SET NULL not valid;

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_region_id_fkey" FOREIGN KEY (region_id) REFERENCES purchase_order_region(id) ON DELETE SET NULL not valid;

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_currency_id_fkey" FOREIGN KEY (currency_id) REFERENCES product_currency(id) ON DELETE SET NULL not valid;

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_contact_person_id_fkey" FOREIGN KEY (contact_person_id) REFERENCES person(id) ON DELETE SET NULL not valid;

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_sign_person_id_fkey" FOREIGN KEY (sign_person_id) REFERENCES person(id) ON DELETE SET NULL not valid;

alter table "public"."purchase_order_drafts" add constraint "purchase_order_drafts_authorized_signer_id_fkey" FOREIGN KEY (authorized_signer_id) REFERENCES person(id) ON DELETE SET NULL not valid;

-- Grant permissions
grant delete on table "public"."purchase_order_drafts" to "anon";
grant insert on table "public"."purchase_order_drafts" to "anon";
grant references on table "public"."purchase_order_drafts" to "anon";
grant select on table "public"."purchase_order_drafts" to "anon";
grant trigger on table "public"."purchase_order_drafts" to "anon";
grant truncate on table "public"."purchase_order_drafts" to "anon";
grant update on table "public"."purchase_order_drafts" to "anon";

grant delete on table "public"."purchase_order_drafts" to "authenticated";
grant insert on table "public"."purchase_order_drafts" to "authenticated";
grant references on table "public"."purchase_order_drafts" to "authenticated";
grant select on table "public"."purchase_order_drafts" to "authenticated";
grant trigger on table "public"."purchase_order_drafts" to "authenticated";
grant truncate on table "public"."purchase_order_drafts" to "authenticated";
grant update on table "public"."purchase_order_drafts" to "authenticated";

grant delete on table "public"."purchase_order_drafts" to "service_role";
grant insert on table "public"."purchase_order_drafts" to "service_role";
grant references on table "public"."purchase_order_drafts" to "service_role";
grant select on table "public"."purchase_order_drafts" to "service_role";
grant trigger on table "public"."purchase_order_drafts" to "service_role";
grant truncate on table "public"."purchase_order_drafts" to "service_role";
grant update on table "public"."purchase_order_drafts" to "service_role"; 