name: Reset Staging Database

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Reset Database
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --yes
          supabase db reset --linked --yes
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
