name: Reset Staging Database

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Disable SMTP for CI
        run: |
          echo "Removing SMTP section to avoid CLI parsing errors..."
          sed -i '/\[auth.email.smtp\]/,/sender_name/d' supabase/config.toml

      - name: Reset Database
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
          supabase db reset --linked <<< 'y'
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
