name: Deploy Migrations to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase Project
        run: supabase link --project-ref ${{ secrets.STAGING_PROJECT_ID }}

      - name: Push Database Migrations
        run: supabase db push
      # - run: supabase db seed
